# Generated by Django 4.1.2 on 2022-11-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dreamreal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastname", models.CharField(max_length=50)),
                ("firstname", models.CharField(max_length=50)),
                ("pid", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("passwd", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "dreamreal",
            },
        ),
    ]
