# Generated by Django 4.1.2 on 2022-11-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_companyacc"),
    ]

    operations = [
        migrations.CreateModel(
            name="companyacc_jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("companyname", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=2000)),
                ("uploaddate", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=200)),
                ("require", models.CharField(max_length=2000)),
                ("benefits", models.CharField(max_length=2000)),
                ("email", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "companyacc_jobs",
            },
        ),
    ]
