# Generated by Django 4.1.2 on 2022-11-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_companyacc_jobs_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyacc_jobs",
            name="salary",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
