# Generated by Django 4.1.2 on 2022-11-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_companyacc_jobs_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("itemname", models.CharField(max_length=50)),
                ("quanty", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "shop",
            },
        ),
    ]
