# Generated by Django 4.1.2 on 2022-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="pid",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
