# Generated by Django 4.1.2 on 2022-11-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_shop_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="shop",
            table="shop",
        ),
    ]
