# Generated by Django 4.1.2 on 2022-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_shop_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="applytable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("company_title", models.CharField(max_length=2000)),
                ("company_uploaddate", models.CharField(max_length=200)),
                ("company_salary", models.CharField(max_length=50)),
                ("company_email", models.CharField(max_length=50)),
                ("company_address", models.CharField(max_length=200)),
                ("user_lastname", models.CharField(max_length=50)),
                ("user_firstname", models.CharField(max_length=50)),
                ("user_skill", models.CharField(max_length=200)),
                ("user_selfintroduction", models.CharField(max_length=2000)),
                ("user_education", models.CharField(max_length=200)),
                ("user_experience", models.CharField(max_length=2000)),
                ("user_email", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "applytable",
            },
        ),
    ]
