# Generated by Django 4.1.2 on 2022-11-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_applytable"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="price",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
